### PR TITLE
Create SentenceLength.yml

### PR DESCRIPTION
**Pull request by alexvonme**
I added a rule to check for how many words there are in each sentence.

### CODE REVIEW

**Comment by ccoVeille** [comment]
You could use this

https://github.com/errata-ai/readability/blob/main/Readability%2FGunningFog.yml#L5-L8

Formula:words
Condition > 20

**Comment by tbazant** [comment]
> I added a rule to check for how many words there are in each sentence.

@alexvonme please update your code to what @ccoVeille suggests

**Comment by alexvonme** [comment]
@ccoVeille Is there a particular reason why you suggest using the Gunning Fog formula over the others in the Readability folder?

**Comment by ccoVeille** [comment]
absolutely none, I found one with a formula that mentioned the number of words and shared the first one

```yaml
extends: metric
message: "Try to keep your sentence short: %s words (less than 20 is recommended)."

formula: |
  words

condition: "> 20"
```

:point_up: this is pseudo-code of course

**Comment by alexvonme** [comment]
In that case, please allow me some time to deliberate on the issue. I'd rather be thorough and test a few configurations before we continue.

**Comment by alexvonme** [comment]
Let's freeze this one until the upstream SUSE/doc-styleguide#299 is resolved. We can make the relevant changes based on the outcome of that.

**Comment by alexvonme** [comment]
This pull request is now moved to #102.

**Pull request closed without merging**
