### PR TITLE
Create SentenceLength.yml

### PR DESCRIPTION
**Pull request by alexvonme**
I added a rule to check for how many words there are in each sentence.

### CODE REVIEW

**Comment by ccoVeille** [comment]
I'm unsure why you closed this PR, but I would like to share the vale package readability could be interesting if you try to achieve something 

https://github.com/errata-ai/readability

**Comment by alexvonme** [comment]
I realized that the repo has a structure in its files which I hadn't adhered to, so I wrote another YAML file that achieves the same goal with #95.

**Comment by alexvonme** [comment]
@ccoVeille Thanks for sharing that repository. However, I don't think openSUSE can adopt one of them since those tend to be a bit controversial. On an individual project basis though, I agree, they could be useful.

**Comment by ccoVeille** [comment]
I'm unsure to understand your needs and your constraints.

But my point remains, if you have a need and find something useful in the repository I shared, you can copy paste the rule you like and adapt them if needed

**Comment by ccoVeille** [comment]
I'm just noticing you opened #90

**Pull request closed without merging**
